version: '3'
services:
  mongo:
    image: mongo:4.4.6
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=abcd
    restart: on-failure
    ports:
      - 27017:27017
  mysql:
    image: mysql:8.0.25
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - '3306:3306'
    expose:
      - '3306'
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=pass
    ports:
      - "5432:5432"
<<<<<<< HEAD
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=P@ssword1234
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
=======
>>>>>>> ffacf8f253fe40aa1d47a173cd93ff1cb11b3f38
